malloc:malloc.c
	rm -rf malloc && gcc -o $@ $<
malloc2:malloc2.c
	rm -rf malloc2 && gcc -o $@ $<
anon:anon.c
	rm -rf anon && gcc -o $@ $<
mmap_file_private:mmap_file_private.c
	rm -rf mmap_file_private && gcc -o $@ $<
mmap_file:mmap_file.c
	rm -f mmap_file && gcc -o $@ $<
mmap:mmap.c
	rm -f mmap && gcc -o $@ $<
