def update_experience_info(resume):
    exp_start = resume[iPos['EXPERIENCE_START_TIME']].strip()
    exp_end = resume[iPos['EXPERIENCE_END_TIME']].strip()
    exp_company = resume[iPos['EXPERIENCE_COMPANY_NAME']].strip()
    exp_company_short = resume[iPos['EXPERIENCE_COMPANY_SHORT_NAME']].strip()
    exp_department = resume[iPos['EXPERIENCE_DEPARTMENT']].strip()
    exp_post_name = resume[iPos['EXPERIENCE_POST_NAME']].strip()
    exp_post_class = resume[iPos['EXPERIENCE_POST_CLASS']].strip()
    exp_post_type = resume[iPos['EXPERIENCE_POST_TYPE']].strip()
    exp_post_rank = resume[iPos['EXPERIENCE_POST_RANK']].strip()
    exp_post_feature = resume[iPos['EXPERIENCE_POST_FEATURE']].strip()
    exp_post_subornates = resume[iPos['EXPERIENCE_POST_SUBORNATES']].strip()
    exp_post_duty = resume[iPos['EXPERIENCE_POST_DUTY']].strip()
    exp_post_summary = resume[iPos['EXPERIENCE_POST_SUMMARY']].strip()
    exp_post_base_salary = resume[iPos['EXPERIENCE_POST_BASE_SALARY']].strip()
    exp_post_deduct_salary = resume[iPos['EXPERIENCE_POST_DEDUCT_SALARY']].strip()
    exp_post_zuoxi = resume[iPos['EXPERIENCE_POST_ZUOXI']].strip()
    exp_post_leave_reason = resume[iPos['EXPERIENCE_POST_LEAVE_REASON']].strip()
    exp_post_provice = resume[iPos['EXPERIENCE_POST_PROVICE']].strip()
    exp_post_city = resume[iPos['EXPERIENCE_POST_CITY']].strip()
    exp_post_district = resume[iPos['EXPERIENCE_POST_DISTRICT']].strip()

    exp_post_reference = resume[iPos['EXPERIENCE_POST_REFERENCE']].strip()
    exp_post_reference_post = resume[iPos['EXPERIENCE_POST_REFERENCE_POST']].strip()
    exp_post_reference_phone = resume[iPos['EXPERIENCE_POST_REFERENCE_PHONE']].strip()
