default:text
text:text.c
	gcc -c -fno-asynchronous-unwind-tables -fno-builtin text.c; ld -static -e start -o text text.o
	






#gcc -c -fno-asynchronous-unwind-tables -fno-builtin text.c; ld -static -e start -o text text.o
