p566_reshape_the_matrix:p566_reshape_the_matrix.cpp
	g++ -std=c++11 -o $@ $<
p53_maximum_subarray:p53_maximum_subarray.cpp
	g++ -std=c++11 -o $@ $<
p27_remove_element:p27_remove_element.cpp
	g++ -std=c++11 -o $@ $<
p31_next_permutation:p31_next_permutation.cpp
	g++ -std=c++11 -o $@ $<
p121_best_time_to_buy_and_sell_stock:p121_best_time_to_buy_and_sell_stock.cpp
	g++ -std=c++11 -o $@ $<
p561_array_partition_1:p561_array_partition_1.cpp
	g++ -std=c++11 -o $@ $<
p54_spiral_matrix:p54_spiral_matrix.cpp
	g++ -std=c++11 -o $@ $<
p40_combination_sum_2:p40_combination_sum_2.cpp
	g++ -std=c++11 -o $@ $<
p39_combination_sum:p39_combination_sum.cpp
	g++ -std=c++11 -o $@ $<
p18:p18.cpp
	g++ -std=c++11 -o $@ $<
p16:p16.cpp
	g++ -std=c++11 -o $@ $<
p15:p15.cpp
	g++ -std=c++11 -o $@ $<
p55:p55.cpp
	g++ -std=c++11 -o $@ $<
p33:p33.cpp
	g++ -std=c++11 -o $@ $<
p48:p48.cpp
	g++ -std=c++11 -o $@ $<
p34:p34.cpp
	g++ -std=c++11 -o $@ $<
p35:p35.cpp
	g++ -std=c++11 -o $@ $<
p1:p1.cpp
	g++ -std=c++11 -o $@ $<
p26:p26.cpp
	g++ -std=c++11 -o $@ $<
p167:p167.cpp
	g++ -std=c++11 -o $@ $<
p169:p169.cpp
	g++ -std=c++11 -o $@ $<
p189:p189.cpp
	g++ -std=c++11 -o $@ $<
p217:p217.cpp
	g++ -std=c++11 -o $@ $<
p219:p219.cpp
	g++ -std=c++11 -o $@ $<
p268:p268.cpp
	g++ -std=c++11 -o $@ $<
p283:p283.cpp
	g++ -std=c++11 -o $@ $<
p414:p414.cpp
	g++ -std=c++11 -o $@ $<
p448:p448.cpp
	g++ -std=c++11 -o $@ $<
p485:p485.cpp
	g++ -std=c++11 -o $@ $<
p532:p532.cpp
	g++ -std=c++11 -o $@ $<
test:test.cpp
	g++ -std=c++11 -o $@ $<
