p454_4sum_2:p454_4sum_2.cpp
	g++ -std=c++11 -o $@ $<
p463_island_perimeter:p463_island_perimeter.cpp
	g++ -std=c++11 -o $@ $<
p500_keyboard_row:p500_keyboard_row.cpp
	g++ -std=c++11 -o $@ $<
p525_contiguous_array:p525_contiguous_array.cpp
	g++ -std=c++11 -o $@ $<
p554_brick_wall:p554_brick_wall.cpp
	g++ -std=c++11 -o $@ $<
p575_distribute_candies:p575_distribute_candies.cpp
	g++ -std=c++11 -o $@ $<
p80_remove_duplicates_from_sorted_array_2:p80_remove_duplicates_from_sorted_array_2.cpp
	g++ -std=c++11 -o $@ $<
p73_set_matrix_zeroes:p73_set_matrix_zeroes.cpp
	g++ -std=c++11 -o $@ $<
p81_search_in_rotated_sorted_array_2:p81_search_in_rotated_sorted_array_2.cpp
	g++ -std=c++11 -o $@ $<
p64_minimum_path_sum:p64_minimum_path_sum.cpp
	g++ -std=c++11 -o $@ $<
p74_search_a_2d_matrix:p74_search_a_2d_matrix.cpp
	g++ -std=c++11 -o $@ $<
p90_subsets_2:p90_subsets_2.cpp
	g++ -std=c++11 -o $@ $<
p118_pascal_triangle1:p118_pascal_triangle1.cpp
	g++ -std=c++11 -o $@ $<
p119_pascal_triangle:p119_pascal_triangle.cpp
	g++ -std=c++11 -o $@ $<
p122_best_time_to_buy_and_sell_stock:p122_best_time_to_buy_and_sell_stock.cpp
	g++ -std=c++11 -o $@ $<
p153_find_minimum_in_rotated_sorted_array:p153_find_minimum_in_rotated_sorted_array.cpp
	g++ -std=c++11 -o $@ $<
p59_spiral_matrix:p59_spiral_matrix.cpp
	g++ -std=c++11 -o $@ $<
p209_minimum_size_subarray_sum:p209_minimum_size_subarray_sum.cpp
	g++ -std=c++11 -o $@ $<
p216_combination_sum:p216_combination_sum.cpp
	g++ -std=c++11 -o $@ $<
p289_game_of_life:p289_game_of_life.cpp
	g++ -std=c++11 -o $@ $<
p442_find_all_duplicates_in_an_array:p442_find_all_duplicates_in_an_array.cpp
	g++ -std=c++11 -o $@ $<
p238_product_of_array_except_self:p238_product_of_array_except_self.cpp
	g++ -std=c++11 -o $@ $<
p560_subarray_sum_equals_k:p560_subarray_sum_equals_k.cpp
	g++ -std=c++11 -o $@ $<
p495_teemo_attacking:p495_teemo_attacking.cpp
	g++ -std=c++11 -o $@ $<
p287_find_the_duplicate_number:p287_find_the_duplicate_number.cpp
	g++ -std=c++11 -o $@ $<
p78_subsets:p78_subsets.cpp
	g++ -std=c++11 -o $@ $<
p75_sort_colors:p75_sort_colors.cpp
	g++ -std=c++11 -o $@ $<
p63_unique_paths:p63_unique_paths.cpp
	g++ -std=c++11 -o $@ $<
p62_unique_paths:p62_unique_paths.cpp
	g++ -std=c++11 -o $@ $<
p79_word_search:p79_word_search.cpp
	g++ -std=c++11 -o $@ $<
p88_merge_sorted_array:p88_merge_sorted_array.cpp
	g++ -std=c++11 -o $@ $<
p120_triangle:p120_triangle.cpp
	g++ -std=c++11 -o $@ $<
p162_find_peak_element:p162_find_peak_element.cpp
	g++ -std=c++11 -o $@ $<
p152_maximum_product_subarray:p152_maximum_product_subarray.cpp
	g++ -std=c++11 -o $@ $<
p66_plus_one:p66_plus_one.cpp
	g++ -std=c++11 -o $@ $<
p56_merge_intervals:p56_merge_intervals.cpp
	g++ -std=c++11 -o $@ $<
p229_majority_element:p229_majority_element.cpp
	g++ -std=c++11 -o $@ $<
p380_insert_delete_getrandom:p380_insert_delete_getrandom.cpp
	g++ -std=c++11 -o $@ $<
p228_summary_ranges:p228_summary_ranges.cpp
	g++ -std=c++11 -o $@ $<
p566_reshape_the_matrix:p566_reshape_the_matrix.cpp
	g++ -std=c++11 -o $@ $<
p53_maximum_subarray:p53_maximum_subarray.cpp
	g++ -std=c++11 -o $@ $<
p27_remove_element:p27_remove_element.cpp
	g++ -std=c++11 -o $@ $<
p31_next_permutation:p31_next_permutation.cpp
	g++ -std=c++11 -o $@ $<
p121_best_time_to_buy_and_sell_stock:p121_best_time_to_buy_and_sell_stock.cpp
	g++ -std=c++11 -o $@ $<
p561_array_partition_1:p561_array_partition_1.cpp
	g++ -std=c++11 -o $@ $<
p54_spiral_matrix:p54_spiral_matrix.cpp
	g++ -std=c++11 -o $@ $<
p40_combination_sum_2:p40_combination_sum_2.cpp
	g++ -std=c++11 -o $@ $<
p39_combination_sum:p39_combination_sum.cpp
	g++ -std=c++11 -o $@ $<
p18:p18.cpp
	g++ -std=c++11 -o $@ $<
p16:p16.cpp
	g++ -std=c++11 -o $@ $<
p15:p15.cpp
	g++ -std=c++11 -o $@ $<
p55:p55.cpp
	g++ -std=c++11 -o $@ $<
p33:p33.cpp
	g++ -std=c++11 -o $@ $<
p48:p48.cpp
	g++ -std=c++11 -o $@ $<
p34:p34.cpp
	g++ -std=c++11 -o $@ $<
p35:p35.cpp
	g++ -std=c++11 -o $@ $<
p1:p1.cpp
	g++ -std=c++11 -o $@ $<
p26:p26.cpp
	g++ -std=c++11 -o $@ $<
p167:p167.cpp
	g++ -std=c++11 -o $@ $<
p169:p169.cpp
	g++ -std=c++11 -o $@ $<
p189:p189.cpp
	g++ -std=c++11 -o $@ $<
p217:p217.cpp
	g++ -std=c++11 -o $@ $<
p219:p219.cpp
	g++ -std=c++11 -o $@ $<
p268:p268.cpp
	g++ -std=c++11 -o $@ $<
p283:p283.cpp
	g++ -std=c++11 -o $@ $<
p414:p414.cpp
	g++ -std=c++11 -o $@ $<
p448:p448.cpp
	g++ -std=c++11 -o $@ $<
p485:p485.cpp
	g++ -std=c++11 -o $@ $<
p532:p532.cpp
	g++ -std=c++11 -o $@ $<
test:test.cpp
	g++ -std=c++11 -o $@ $<
