p169:p169.cpp
	g++ -std=c++11 -o $@ $<
p189:p189.cpp
	g++ -std=c++11 -o $@ $<
p217:p217.cpp
	g++ -std=c++11 -o $@ $<
p219:p219.cpp
	g++ -std=c++11 -o $@ $<
p268:p268.cpp
	g++ -std=c++11 -o $@ $<
p283:p283.cpp
	g++ -std=c++11 -o $@ $<
p414:p414.cpp
	g++ -std=c++11 -o $@ $<
p448:p448.cpp
	g++ -std=c++11 -o $@ $<
p485:p485.cpp
	g++ -std=c++11 -o $@ $<
p532:p532.cpp
	g++ -std=c++11 -o $@ $<
